apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: bookserv
  template:
    metadata:
      labels: 
        app: bookserv
    spec:
      containers:
      #  grpc service
        - name: bookserv
          image: alex/bookserv:1.0.0
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: bookserv-configmap
                  key: postgres-host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: bookserv-configmap
                  key: postgres-port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres-db-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key:  postgresql-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgresql-password      
          ports:
            - name: bookserv
              containerPort: 9000
              protocol: TCP
              
        # gateway for grpc service
        - name: bookservgw
          image: alex/bookservgw:1.0.0
          imagePullPolicy: "IfNotPresent"
          env:
            - name: GW_HOST
              value: "0.0.0.0"
            - name: GRPC_HOST
              value: "localhost"
            - name: GRPC_PORT
              value: "9000"
          ports:
            - name: bookservgw
              containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: bookserv-svc
spec:
  type: ClusterIP
  ports:
    - name: bookserv
      port: 9000
      targetPort: bookserv
      protocol: TCP
    - name: bookservgw
      port: 8080
      targetPort: bookservgw
      protocol: TCP
  selector:
    app: bookserv
